export type BookItemProps = {
  bookCover: string;
  type: string;
  star?: number;
  title: string;
  author: string;
  onClick: () => void;
};

export enum BookGenres {
  "Art & photography",
  "Architecture",
  "Art book",
  "Graphic Design",
  "Religion, Culture",
  "Photography",
  "Decorative Arts & Design",
  "Drawing & Painting",
  "Fashion",
  "Sculpture",
  "Music",
  "Performing Arts",
  "Collections, Catalogs & Exhibitions",
  "Biographies & Memoirs",
  "Business Leaders",
  "Celebrities & Famous People",
  "Historical, Political & Military",
  "Art & Literature",
  "True Crime",
  "Sports & Outdoor",
  "Business & Economics",
  "Finance & Economics",
  "Investment & Entrepreneurship",
  "Job - Career",
  "Management - Leadership",
  "Marketing - Sales",
  "Processes & Infrastructure",
  "Skills",
  "Guide / How-to & Self-help",
  "Communication & Social Skills",
  "Creativity",
  "Emotions",
  "Motivational",
  "Personal Improvement",
  "Relationship",
  "Stress Management",
  "Children’s Books",
  "Coloring",
  "Early Learning",
  "Activity",
  "Dictionary",
  "Education - Teaching",
  "ELTs",
  "Primary School",
  "High School",
  "College",
  "Postgraduate",
  "Fantasy",
  "Science Fiction",
  "Literature",
  "Action & Adventure",
  "Classic",
  "Contemporary",
  "Dramas & Plays",
  "Historical Fiction",
  "Humor & Satire",
  "Literary",
  "Mystery, Thriller & Suspense",
  "Mythology & Folk Tales",
  "Romance",
  "Short Stories & Anthologies",
  "Poetry",
  "History & Criticism",
  "Comics & Graphic Novels",
  "Women’s Fiction",
  "Science Fiction & Fantasy",
  "Magazines - Catalogue",
  "Medical Books",
  "Parenting & Relationships",
  "Reference",
  "Crafts & Hobbies",
  "Health, Fitness & Sports",
  "Home Living",
  "Psychology",
  "Professions",
  "Atlases - Encyclopedia",
  "🌐 Science - Technology",
  "Astronomy & Space Science",
  "Environment",
  "Agriculture & Forestry",
  "Mathematics",
  "Nature & Ecology",
  "Human & Biology Science",
  "Internet - Computer",
  "History & Social Sciences",
  "Philosophy",
  "Politics & Current Affairs",
  "Sociology",
  "History",
  "Travel & Holiday",
  "Cookbook, Food & Wine",
  "Diets",
  "Beverages",
  "Ingredients, Methods & Appliances",
  "Baking - Desserts",
  "Comic, Manga, Light Novel",
  "Mystery - Horror",
  "Agriculture - Forestry - Fisheries",
  "Gardening",
  "Agriculture",
  "Forestry",
  "Fisheries",
  "Foreign Books",
  "Religion - Spirituality",
  "Blockchain"
}
